import { shuffle } from 'lodash'

export default shuffle([
  {
    name: 'Sarah Drasner',
    city: 'Denver, CO, USA',
    languages: ['en'],
    work: {
      role: 'Director of Engineering, Core Developer Web',
      org: 'Google',
      orgUrl: 'https://google.com',
    },
    github: 'sdras',
    twitter: 'sarah_edo',
    codepen: 'sdras',
    reposOfficial: ['vuejs.org'],
    reposPersonal: [
      'vue-vscode-snippets',
      'intro-to-vue',
      'vue-vscode-extensionpack',
      'ecommerce-netlify',
    ],
    links: ['https://sarah.dev/'],
  },
  {
    name: 'Chris Fritz',
    title: 'Good Word Putter-Togetherer',
    city: 'Durham, NC, USA',
    languages: ['en', 'de'],
    github: 'chrisvfritz',
    twitter: 'chrisvfritz',
    work: {
      role: 'Educator & Consultant',
    },
    reposPersonal: ['vue-enterprise-boilerplate'],
  },
  {
    name: 'Blake Newman',
    title: 'Performance Specializer & Code Deleter',
    city: 'London, UK',
    languages: ['en'],
    work: {
      role: 'Software Engineer',
      org: 'Attest',
      orgUrl: 'https://www.askattest.com/',
    },
    github: 'blake-newman',
    twitter: 'blakenewman',
  },
  {
    name: 'kingwl',
    title: 'New Bee',
    city: 'Beijing, China',
    languages: ['zh'],
    work: {
      role: 'Software Development Engineer',
      org: 'Chaitin',
      orgUrl: 'https://chaitin.cn/',
    },
    github: 'kingwl',
    reposOfficial: ['vue'],
  },
  {
    name: 'Alan Song',
    title: 'Regent of Routing',
    city: 'Hangzhou, China',
    languages: ['zh', 'en'],
    work: {
      role: 'Cofounder',
      org: 'Futurenda',
      orgUrl: 'https://www.futurenda.com/',
    },
    github: 'fnlctrl',
    reposOfficial: ['vue-router'],
  },
  {
    name: 'defcc',
    title: 'Details Deity & Bug Surgeon',
    city: 'Chongqing, China',
    languages: ['zh', 'en'],
    github: 'defcc',
    work: {
      org: 'zbj.com',
      orgUrl: 'http://www.zbj.com/',
    },
  },
  {
    name: 'gebilaoxiong',
    title: 'Issue Annihilator',
    city: 'Chongqing, China',
    languages: ['zh', 'en'],
    github: 'gebilaoxiong',
    work: {
      org: 'zbj.com',
      orgUrl: 'http://www.zbj.com/',
    },
  },
  {
    name: 'Denis Karabaza',
    title: 'Director of Directives (Emoji-Human Hybrid)',
    city: 'Dubna, Russia',
    languages: ['ru', 'en'],
    github: 'simplesmiler',
    twitter: 'simplesmiler',
    work: {
      role: 'Software Engineer',
      org: 'Neolant',
      orgUrl: 'http://neolant.ru/',
    },
  },
  {
    name: 'Edd Yerburgh',
    title: 'Testatron Alpha 9000',
    city: 'London, UK',
    languages: ['en'],
    github: 'eddyerburgh',
    twitter: 'EddYerburgh',
    work: {
      role: 'Full Stack Developer',
    },
    reposOfficial: ['vue-test-utils'],
    reposPersonal: ['avoriaz'],
    links: ['https://www.eddyerburgh.me'],
  },
])
